[package]
name = "json_schema"
version = "1.6.10"
description = "Generated types based on the JSON-Schema for json_schema"
license = "Apache-2.0"

[dependencies]
serde_json = "1.0"

  [dependencies.serde]
  version = "1.0"
  features = [ "derive" ]
