[package]
name = "json_schema"
version = "1.6.9"
description = "Generated typings to be used in rust programs and libraries."
license = "Apache-2.0"

[dependencies]
serde_json = "1.0"

  [dependencies.serde]
  version = "1.0"
  features = [ "derive" ]
