version: 2

aliases:
  # -------------------------
  #      ALIASES: Caches
  # -------------------------
  - &restore-deps-cache
    key: deps-cache-{{ checksum "package.json" }}

  - &save-deps-cache
    key: deps-cache-{{ checksum "package.json" }}
    paths:
      - ~/project/node_modules

  # -------------------------
  #  ALIASES: Branch Filters
  # -------------------------
  - &filter-only-master
    branches:
      only: master
  - &filter-only-semantic-pr
    branches:
      only:  /^(pull|fix|feat|dependabot)\/.*$/

defaults: &defaults
  working_directory: ~/project

jobs:
  test:
    <<: *defaults
    docker:
      - image: circleci/node:13
    steps:
      - checkout
      - restore_cache: *restore-deps-cache
      - run: npm install
      - run: npm install codecov
      - run: npm test
      - run: ./node_modules/.bin/codecov
      - save_cache: *save-deps-cache

  release:
    <<: *defaults
    docker:
      - image: circleci/node:13
    steps:
      - checkout
      - restore_cache: *restore-deps-cache
      - run: npm install
      - run: ./node_modules/.bin/semantic-release
      - save_cache: *save-deps-cache

workflows:
  version: 2
  analysis:
    jobs:
      - test:
          filters: *filter-only-semantic-pr

  release:
    jobs:
      - test:
          filters: *filter-only-master
      - hold:
          filters: *filter-only-master
          type: approval
          requires:
            - test
      - release:
          filters: *filter-only-master
          context: sem-rel-json-schema-tools
          requires:
            - hold
