name: CI
permissions:
  contents: read
jobs:
  test:
    uses: json-schema-tools/foundation/.github/workflows/node-ci.yml@b9a036e0b64a3fd9982d0eab904f5cb1227625df # v1.0.0
    with:
      build-command: npm run build
      post-build-command: git diff --exit-code -- index.js index.d.ts index.py json_schema.go schema.json src/index.ts src/lib.rs
      test-command: npm test -- --runInBand
      rust-tests: true
  commitlint:
    uses: json-schema-tools/foundation/.github/workflows/commitlint.yml@b9a036e0b64a3fd9982d0eab904f5cb1227625df # v1.0.0
    permissions:
      contents: read
      pull-requests: read
'on':
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch: null
